baseURL = 'https://daily.gagelara.com/'
canonifyURLs = true
relativeURLs = true
languageCode = 'en-us'
title = "Gage Lara's Daily Notes"
theme = 'github-style'

[params]
  author = "Gage Lara"
  description = "NixOS, DevOps, and Cloud enthusiast. I also make music and TTRPG stuff. "
  github = "metamageia"
  linkedin = "gage-lara"
  email = "gageallenlara@gmail.com"
  url = "https://links.gagelara.com"
  keywords = "blog"
  rss = true
  lastmod = true
  favicon = "/images/github-mark.png"
  avatar = "/images/avatar.png"
  headerIcon = "/images/avatar.png"
  location = "El Dorado, Ks"
  enableGitalk = false
  enableSearch = true
